spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sailing
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
env:
  dev1

#修改负载均衡得规则
#PRODUCT:
 # ribbon:
  #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule