spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sailing
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
  rabbitmq:
    host: 172.20.33.208
    port: 5672
    username: admin
    password: admin
env:
  test
girl:
  name: lili
  age: 24
