spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sailing
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
   rabbitmq:
    host: 172.20.33.208
    port: 5672
    username: admin
    password: admin
  jpa:
    show-sql: true
